/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.3 at Thu Jul 11 11:43:56 2019. */

#ifndef PB_MYPROTO_PB_H_INCLUDED
#define PB_MYPROTO_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _MyMessage {
    char name[40];
    pb_size_t ids_count;
    int32_t ids[5];
/* @@protoc_insertion_point(struct:MyMessage) */
} MyMessage;

/* Default values for struct fields */

/* Initializer values for message structs */
#define MyMessage_init_default                   {"", 0, {0, 0, 0, 0, 0}}
#define MyMessage_init_zero                      {"", 0, {0, 0, 0, 0, 0}}

/* Field tags (for use in manual encoding/decoding) */
#define MyMessage_name_tag                       1
#define MyMessage_ids_tag                        2

/* Struct field encoding specification for nanopb */
extern const pb_field_t MyMessage_fields[3];

/* Maximum encoded size of messages (where known) */
#define MyMessage_size                           97

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define MYPROTO_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
