/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.3 at Thu Jul 11 11:43:56 2019. */

#include "myproto.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t MyMessage_fields[3] = {
    PB_FIELD(  1, STRING  , SINGULAR, STATIC  , FIRST, MyMessage, name, name, 0),
    PB_FIELD(  2, INT32   , REPEATED, STATIC  , OTHER, MyMessage, ids, name, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
