/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.3 at Wed Jul 17 13:19:30 2019. */

#include "rpc.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t add_fields[3] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, add, a, a, 0),
    PB_FIELD(  2, INT32   , SINGULAR, STATIC  , OTHER, add, b, a, 0),
    PB_LAST_FIELD
};

const pb_field_t singlein_fields[2] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, singlein, response, response, 0),
    PB_LAST_FIELD
};

const pb_field_t ack_fields[2] = {
    PB_FIELD(  1, BOOL    , SINGULAR, STATIC  , FIRST, ack, ack, ack, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
