/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.3 at Thu Jul 18 14:16:48 2019. */

#ifndef PB_RPC_PB_H_INCLUDED
#define PB_RPC_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _ack_nak {
    bool ack;
/* @@protoc_insertion_point(struct:ack_nak) */
} ack_nak;

typedef struct _command {
    char command[5];
/* @@protoc_insertion_point(struct:command) */
} command;

typedef struct _single_int {
    int32_t response;
/* @@protoc_insertion_point(struct:single_int) */
} single_int;

typedef struct _sum_rpc {
    int32_t a;
    int32_t b;
/* @@protoc_insertion_point(struct:sum_rpc) */
} sum_rpc;

/* Default values for struct fields */

/* Initializer values for message structs */
#define command_init_default                     {""}
#define sum_rpc_init_default                     {0, 0}
#define single_int_init_default                  {0}
#define ack_nak_init_default                     {0}
#define command_init_zero                        {""}
#define sum_rpc_init_zero                        {0, 0}
#define single_int_init_zero                     {0}
#define ack_nak_init_zero                        {0}

/* Field tags (for use in manual encoding/decoding) */
#define ack_nak_ack_tag                          1
#define command_command_tag                      1
#define single_int_response_tag                  1
#define sum_rpc_a_tag                            1
#define sum_rpc_b_tag                            2

/* Struct field encoding specification for nanopb */
extern const pb_field_t command_fields[2];
extern const pb_field_t sum_rpc_fields[3];
extern const pb_field_t single_int_fields[2];
extern const pb_field_t ack_nak_fields[2];

/* Maximum encoded size of messages (where known) */
#define command_size                             7
#define sum_rpc_size                             22
#define single_int_size                          11
#define ack_nak_size                             2

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define RPC_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
